branch-defaults:
  master:
    environment: frontend-nick
environment-defaults:
  frontend-nick:
    branch: null
    repository: null
global:
  application_name: ASF-front
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-1::platform/Node.js running on
    64bit Amazon Linux/4.5.0
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
